### ISSUE TITLE
upload artifacts as bundle

### ISSUE THREAD

**Issue by igreenfield** [packagemgmt/repositorytools#35]
If you try to load 2 artifacts with the same groupId and artifactId you will get bad request: 
```html
<html>
  <body>
     <error>Repository with ID= does not allow updating artifacts.</error>
  </body>
</html>
```
The lib try to upload them one by one so the second one will try to update the first.
this should be uploaded as one. 
as describe in this: [How-can-I-programatically-upload-an-artifact-into-Nexus](https://support.sonatype.com/hc/en-us/articles/213465818-How-can-I-programatically-upload-an-artifact-into-Nexus-)

**Comment by stardust85** [comment]
This is not a bug, it is a setting of nexus. Triple (groupId, artifactId, version) have to be unique for each artifact. Try a different version.
